### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by jpage-godaddy**
- Enable latest mocha version
- Bump `elasticsearch` client
- Bump `mochawesome`
- Bump `rewire` and move to dev dependencies

### CODE REVIEW

**Comment by jpage-godaddy** [comment]
The integration tests are trying to connect to an elasticsearch instance that doesn't exist, so I'm not sure what the best strategy is for doing the integration testing.

**Comment by smagar-godaddy** [comment]
@manojnextdoor @mpahuja can we get this beta published? I can try that beta version in one of our repos.

**Comment by mpahuja** [comment]
sure thing I will merge this and publish a new version of it

**Comment by mpahuja** [comment]
@jpage-godaddy @sushilmagars mocha-elk-reporter@3.0.0 was just published for your use

**Pull request merged**
