### PR TITLE
Avoid logging Elasticsearch username & password.

### PR DESCRIPTION
**Pull request by ounis**
Just for security reasons.

### CODE REVIEW

**Comment by ounis** [comment]
Just for security reasons.

**Comment by ounis** [comment]
Could this be merged please, it's important for my deployment security checks.

**Comment by ounis** [comment]
I also added Travis CI yml file to run tests automatically check https://travis-ci.org/ounis/mocha-elk-reporter

**Comment by mpahuja** [comment]
Somehow didn't get any notification about this PR. Will push a new version soon

**Comment by mpahuja** [comment]
v2.2.0 was published with these changes

**Comment by ounis** [comment]
> Somehow didn't get any notification about this PR. Will push a new version soon

Great! thanks a lot.

**Pull request merged**
